# Generated by Django 3.1.7 on 2021-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_auto_20210328_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
