# Generated by Django 3.1.7 on 2021-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courier', '0003_auto_20210329_0538'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION has_intersection(time [][], time [][]) RETURNS BOOLEAN as
            $$
            DECLARE
                x time[];
                y time[];
            BEGIN
                FOREACH x SLICE 1 IN ARRAY $1
                    LOOP
                        FOREACH y SLICE 1 IN ARRAY $2
                            LOOP
                                IF (x[1] >= y[1] AND x[1] < y[2]) OR (x[2] > y[1] AND x[2] <= y[2]) then
                                    return true;
            
                                END IF;
                            END LOOP;
                    END LOOP;
                RETURN false;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
    ]
