# Generated by Django 3.1.7 on 2021-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_compare_arrays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_type',
            field=models.CharField(choices=[('foot', 10), ('bike', 15), ('car', 50)], max_length=30),
        ),
    ]
