# Generated by Django 3.1.7 on 2021-03-28 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=2), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
