# Generated by Django 3.1.7 on 2021-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
