name: Build

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.7'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          sudo apt-get install gdal-bin -y
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrate
        run:  python manage.py migrate --settings=config.settings_test
      - name: Run django tests
        run:  python manage.py test --settings=config.settings_test