name: Deploy dokku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: deploy
        name: Deploy to dokku
        uses: dokku/github-action@0.0.11
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: 'my-dokku-host.com'
            app-name: 'my-dokku-app'